faretracker/config/routes.rb
Rails.application.routes.draw do
  resources :trips

end

faretracker/app/models/flight_analyst.rb
require 'byebug'

class FlightAnalyst

  def initialize(parsed_flight, number_of_results)
    @parsed_flight = parsed_flight.options(number_of_results)
    @number_of_results = number_of_results
  end

  def prices
    @parsed_flight.map{|flight| flight[-1][1..-1].to_f.ceil}
  end

  def average_price
    prices.reduce(:+)/@number_of_results
  end

  def median
    if @number_of_results.odd?
      prices[@number_of_results/2]
    else
      prices[(@number_of_results/2 - 1)..@number_of_results/2].reduce(:+)/2
    end
  end

  def low
    prices[0]
  end
end

faretracker/app/models/flight_fetcher.rb
require 'httparty'
require 'byebug'

class FlightFetcher
  attr_reader :itineraries

  def initialize(start_code, end_code, date)
    @start_code = start_code
    @end_code = end_code
    @date = date
    @itineraries = get_data
  end

  def get_data
    HTTParty.post("https://www.googleapis.com/qpxExpress/v1/trips/search?key=#{ENV["GOOGLE_KEY"]}",
    :body =>  {
        "request": {
          "passengers": {
            "kind": "qpxexpress#passengerCounts",
            "adultCount": 1,
            "childCount": 0,
            "infantInLapCount": 0,
            "infantInSeatCount": 0,
            "seniorCount": 0
          },
          "slice": [
            {
              "kind": "qpxexpress#sliceInput",
              "origin": "#{@start_code}",
              "destination": "#{@end_code}",
              "date": "#{@date}",
              "maxStops": 1,
              "preferredCabin": "COACH",
            }
          ],
          "refundable": false,
          "solutions": 10
        }
      }.to_json,
      :headers => { 'Content-Type' => 'application/json' })
  end

end

faretracker/app/models/flight_parser.rb
require './flight_fetcher.rb'
require 'time'

class FlightParser
  attr_reader :results

  def initialize(flight)
    @results = flight.itineraries
  end

  def price(trip_num)
    cost = results["trips"]["tripOption"][trip_num]["saleTotal"]
    new_cost = cost[3..-1]
    "$#{new_cost}"
  end

  def carrier(trip_num, leg_num)
    results["trips"]["tripOption"][trip_num]["slice"][0]["segment"][leg_num]["flight"]["carrier"]
  end

  def number(trip_num, leg_num)
    results["trips"]["tripOption"][trip_num]["slice"][0]["segment"][leg_num]["flight"]["number"]
  end

  def origin(trip_num, leg_num)
    results["trips"]["tripOption"][trip_num]["slice"][0]["segment"][leg_num]["leg"][0]["origin"]
  end

  def destination(trip_num, leg_num)
    results["trips"]["tripOption"][trip_num]["slice"][0]["segment"][leg_num]["leg"][0]["destination"]
  end

  def departs_on(trip_num, leg_num)
    day = results["trips"]["tripOption"][trip_num]["slice"][0]["segment"][leg_num]["leg"][0]["departureTime"]
    day[0..9]
  end

  def departs_at(trip_num, leg_num)
    time = results["trips"]["tripOption"][trip_num]["slice"][0]["segment"][leg_num]["leg"][0]["departureTime"]
    Time.parse(time).strftime '%I:%M %p'
  end

  def total_time(trip_num)
    minutes = results["trips"]["tripOption"][trip_num]["slice"][0]["duration"].to_f
    hours = (minutes/60.0).round(1)
    "#{hours} hours"
  end

  def itinerary(num)
    trip_counter = num
    leg_counter = 0
    stops = []
    until results["trips"]["tripOption"][trip_counter]["slice"][0]["segment"][leg_counter] == nil
      next_stop = {}
      next_stop["leg"] = leg_counter+1
      next_stop["origin"] = origin(trip_counter, leg_counter)
      next_stop["destination"] = destination(trip_counter, leg_counter)
      next_stop["flight_number"] = "#{carrier(trip_counter, leg_counter)} #{number(trip_counter, leg_counter)}"
      next_stop["departure_time"] = "#{departs_at(trip_counter, leg_counter)}"
      stops << next_stop
      leg_counter += 1
    end
    stops << total_time(trip_counter)
    stops << price(trip_counter)
    stops
  end

  def options(num)
    counter = 0
    trips = []
    until counter == num
      trips<<itinerary(counter)
      counter += 1
    end
    trips
  end
end

faretracker/app/models/flight_reporter.rb
require './flight_fetcher.rb'
require './flight_parser.rb'
require './flight_analyst.rb'

class FlightReporter

  attr_reader :parsed_flight, :number_of_results

  def initialize(parsed_flight, flight_analyst, number_of_results)
    @parsed_flight = parsed_flight.options(number_of_results)
    @flight_analyst = flight_analyst
    @number_of_results = number_of_results
  end


  def show_results
    lines = ""
    @parsed_flight.each do |trip|
      lines<<"#{trip[-1]}"
      lines<<" || #{trip[-2]}"
      lines<<" || #{trip[0]["origin"]} -> #{trip[0]["destination"]} @ #{trip[0]["departure_time"]}"
      lines<<" || #{trip[1]["origin"]} -> #{trip[1]["destination"]} @ #{trip[1]["departure_time"]}" unless trip[1].nil?
      lines<<" || #{trip[0]["flight_number"][0..1]}"
      lines<<"\n"
    end
    translate(lines)
  end

  def translate(text)
    airline_codes.keys.each do |code|
      text.gsub!(code, airline_codes[code])
    end
    text
  end

  def airline_codes
    {"AA"=>"American", "B6"=>"JetBlue", "DL"=>"Delta", "F9"=>"Frontier", "FL"=>"AirTran",
      "WN"=>"Southwest","UA"=>"United"}
  end

  def show_stats
    stats = ""
    stats<<"Average Price: #{@flight_analyst.average_price}\n"
    stats<<"Median Price: #{@flight_analyst.median}\n"
    stats<<"Low Price: #{@flight_analyst.low}\n"
    stats
  end
end

faretracker/app/models/trip.rb
class Trip < ActiveRecord::Base
end

faretracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

faretracker/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:origin, :destination, :date, :active)
    end
end

faretracker/app/helpers/application_helper.rb
module ApplicationHelper
end

faretracker/app/helpers/trips_helper.rb
module TripsHelper
end

faretracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Faretracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

faretracker/app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

faretracker/app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

faretracker/app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.origin %></td>
        <td><%= trip.destination %></td>
        <td><%= trip.date %></td>
        <td><%= trip.active %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

faretracker/app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

faretracker/app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @trip.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trip.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @trip.date %>
</p>

<p>
  <strong>Active:</strong>
  <%= @trip.active %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>